// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1TXFS9XuBbpqxa-eeBrPfUt1G74EvOa8',
    appId: '1:552768293663:web:b9f1f69a9408fa9fd7fe2a',
    messagingSenderId: '552768293663',
    projectId: 'servis-takip-d1efd',
    authDomain: 'servis-takip-d1efd.firebaseapp.com',
    storageBucket: 'servis-takip-d1efd.firebasestorage.app',
    measurementId: 'G-K2T50QJRBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2EbGl9qg5FZeEEZdqqHIwg86z9VLgC20',
    appId: '1:552768293663:android:31e953b129f91ae0d7fe2a',
    messagingSenderId: '552768293663',
    projectId: 'servis-takip-d1efd',
    storageBucket: 'servis-takip-d1efd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCszERoVxlTdjKwhq1RSba4HVwtIQaF5O8',
    appId: '1:552768293663:ios:da70a1bd6a0e6931d7fe2a',
    messagingSenderId: '552768293663',
    projectId: 'servis-takip-d1efd',
    storageBucket: 'servis-takip-d1efd.firebasestorage.app',
    iosBundleId: 'com.servistakip.servisTakip',
  );
}
